version: '3.2'

services:

  application:
    build: src
    ports:
      - 35585:80
    volumes:
      # Re-use local composer cache via host-volume
      # Mount source-code for development
      - ./:/app
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.11
    hostname: calendarproj_db
    ports:
      - 59699:3306
    environment:
      - MYSQL_ROOT_PASSWORD=verysecret
      - MYSQL_DATABASE=calendarproj
      - MYSQL_USER=calendarproj
      - MYSQL_PASSWORD=secret

  #pgsql:
  #  image: postgres:9.5
  #  environment:
  #    - POSTGRES_DB=yii2advanced
  #    - POSTGRES_USER=yii2advanced
  #    - POSTGRES_PASSWORD=secret